MxOnline/urls.py
#_*_ encoding:utf-8 _*_

"""MxOnline URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
import xadmin
from django.views.static import serve
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView
from users.views import IndexView
from organization.views import OrgView
from MxOnline.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$', IndexView.as_view(), name="index"), #process static file
    url('^login/$', LoginView.as_view(), name="login"),
    url('^logout/$', LogoutView.as_view(), name="logout"),
    url('^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),
    #organization url setting
    url(r'^org/', include('organization.urls', namespace="org")),
    #the process function that configure the upload file's access
    url(r'^media/(?P<path>.*)', serve, {"document_root":MEDIA_ROOT}),

    # Production mode
    # url(r'^static/(?P<path>.*)', serve, {"document_root": STATIC_ROOT}),
    # courses relative url setting
    url(r'^course/', include('courses.urls', namespace="course")),
    # teacher relative url setting
    url(r'^teacher/', include('courses.urls', namespace="teacher")),
    # user relative url setting
    url(r'^users/', include('users.urls', namespace="users")),

    #ueditor related url
    url(r'^ueditor/',include('DjangoUeditor.urls' ))
]
#404 page set up
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Yujia Lian'
__date__ = '6/25/17 1:01 PM'


from django.conf.urls import url, include
from .views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentView, AddCommentsView, VideoPlayView

urlpatterns = [
    #courses list
    url(r'^list/$', CourseListView.as_view(), name="course_list"),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="course_detail"),

    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name="course_info"),

    #course comments
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name="course_comment"),

    #add course comments
    url(r'^add_comment/$', AddCommentsView.as_view(), name="add_comment"),

    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name="video_play"),
]

apps/organization/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Yujia Lian'
__date__ = '6/21/17 9:50 AM'

from django.conf.urls import url, include
from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView
from .views import AddFavView, TeacherListView, TeacherDetailView
urlpatterns = [
    #course organization list
    url(r'^list/$', OrgView.as_view(), name="org_list"),
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),

    #collection
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),

    #Teacher list page
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),

    #teacher detail page
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail")
]

apps/users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Yujia Lian'
__date__ = '7/4/17 1:22 AM'

from django.conf.urls import url, include
from .views import UserinfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView
from .views import MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseTView, MyMessageView

urlpatterns = [
    #User detail page
    url(r'^info/$', UserinfoView.as_view(), name="user_info"),

    #User head upload
    url(r'^image/upload/$', UploadImageView.as_view(), name= 'image_upload'),

    #user center change password
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update'),

    #send email verify code
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),

    # modify email
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    #My courses
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),

    # My course collection
    url(r'^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),

    # My teacher collection
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),

    # My course collection
    url(r'^myfav/course/$', MyFavCourseTView.as_view(), name='myfav_course'),

    # My message
    url(r'^mymessage/$', MyMessageView.as_view(), name='mymessage')
]

apps/courses/models.py
#_*_ encoding:utf-8 _*_
from __future__ import unicode_literals
from datetime import datetime
from organization.models import CourseOrg, Teacher
from django.db import models
from DjangoUeditor.models import UEditorField
# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name="Course organization", null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u"Course name")
    teacher = models.ForeignKey(Teacher, verbose_name="Professor", null=Teacher, blank=True)
    desc = models.CharField(max_length=300, verbose_name=u"Course description")
    category = models.CharField(default=u"back end",max_length=20, verbose_name=u"Course category")
    detail = UEditorField(verbose_name="Course detail",width=600, height=300, imagePath="courses/ueditor/", filePath="courses/ueditor/", default="")
    is_banner = models.BooleanField(default=False, verbose_name="add banner")
    degree = models.CharField(choices=(("cj", "Begining level"),("zj", "Middle level"), ("gj", "High level")),
                              max_length=2)
    learn_times = models.IntegerField(default=0, verbose_name=u"Learning time(In minutes)")
    students = models.IntegerField(default=0, verbose_name=u"Total enrolled students")
    fav_nums = models.IntegerField(default=0, verbose_name=u"Favorite number")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"Cover", max_length=100)
    click_num = models.IntegerField(default=0, verbose_name=u"Click times")
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u"Add time")
    tags = models.CharField(default="", verbose_name="Course tag", max_length=100)
    you_need_know = models.CharField(default="", max_length=300, verbose_name="Course requirement")
    teacher_notice = models.CharField(default="", max_length=300, verbose_name="Teacher notice")

    class Meta:
        verbose_name = u"Course"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_chapter_nums(self):
        #get the chapter nums
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        #get course all chapter
        return self.lesson_set.all()

    def get_relate_courses(self):

        return self.course_org.course_set[:5]


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"Course")
    name = models.CharField(max_length=100, verbose_name=u"Chapter name")
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u"Add time")

    class Meta:
        verbose_name = u"Chapter"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


    def get_lesson_video(self):
        #get chapter videos
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u"Chapter")
    name = models.CharField(max_length=100, verbose_name=u"Video name")
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u"Add time")
    url = models.CharField(max_length=200, default="", verbose_name="url")
    learn_times = models.IntegerField(default=0, verbose_name=u"Learning time(In minutes)")


    class Meta:
        verbose_name = u"Course video"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"Course")
    name = models.CharField(max_length=100, verbose_name=u"name")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"Resource files", max_length=100)
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u"Add time")

    class Meta:
        verbose_name = u"Course resources"
        verbose_name_plural = verbose_name


class BannerCourse(Course):
    class Meta:
        verbose_name = "Banner course"
        verbose_name_plural = verbose_name
        proxy = True

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}Geek online Education{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>Contact：<b>yujia.lian001@gmail.com</b></p></div>
					<!--登录后跳转-->
                        {% if request.user.is_authenticated %}
                            <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">Go to user center</a>
	                                <a class="fr" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </div>
                        </div>
                            <a href="{% url 'users:mymessage' %}">
                                <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                            </a>
                        {% else %}
                            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Register</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">Login</a>
                        {% endif %}
				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                Courses
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">Courses</li>
                                <li data-value="org">Organizations</li>
                                <li data-value="teacher">Teachers</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="Please enter keywords"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li {% if request.path == '/' %}class="active"{% endif %}><a href="{% url 'index' %}">Main page</a></li>
							<li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
								<a href="{% url 'course:course_list' %}">
									Courses<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
								<a href="{% url 'org:teacher_list' %}">Teachers</a>
							</li>
							<li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %} ><a href="{% url 'org:org_list' %}">Organizations</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">Main page</a>></li>
                <li>Organization</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
{% endblock %}
<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">3042169199</p><p class="time">Monday to friday 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">2017 Geek online education all rights reserved</span>
                <span class="fr">Developer: yujia.lian001@gmail.com</span>
			</div>
		</div>
	</footer>
<section>

</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
{% block custom_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Geek online education{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banners %}
                            <li>
                                    <a href="{% url 'org:org_list' %}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}

						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature1.png' %}"/>
					<p class="center">Professional</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature2.png' %}"/>
					<p class="center">Frontiers</p>
				</li>
				<li class="feature3">
					<img class="pic" src="{% static 'images/feature3.png' %}"/>
					<p class="center">Expertise</p>
				</li>
				<li class="feature4">
					<img class="pic" src="{% static 'images/feature4.png' %}"/>
					<p class="center">Reliable</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>Courses</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
						<p class="fisrt_word">Stay hungry<br/>Stay foolish</p>
						<a class="more" href="{% url 'course:course_list' %}">More courses ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    {% for banner_course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course:course_detail' banner_course.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                                        </a>
                                    </li>
                                    {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="{{ course.name }}"><font size="2.5" color="#6495ed">{{ course.name }}</font></h2>
                                    </a>
                                    <span class="fl"><i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">Students:{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>Organizations</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
						<p class="fisrt_word">Top univeristy<br/>Certification</p>
						<a class="more" href="{% url 'org:org_list' %}">More ></a>
					</div>
					<div class="right">
						<ul>
                            {% for org in course_orgs %}
                                <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block custom_title %}Organization-Main Page{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">

            {% if request.user.is_authenticated %}
                <div class="top">
				    <div class="wp">
					    <div class="fl"><p>Contact：<b>3042169199</b></p></div>
					    <!--登录后跳转-->
                            {% if request.user.is_authenticated %}
                            <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">Go to user center</a>
	                                <a class="fr" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </div>
                        </div>
                            <a href="{% url 'users:mymessage' %}">
                                <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                            </a>
                        {% else %}
                            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Register</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">Login</a>
                        {% endif %}


				    </div>
			    </div>
            {% else %}
                <div class="top">
				<div class="wp">
					<div class="fl"><p>Contact：<b>3042169199</b></p></div>
					<!--登录后跳转-->
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Register</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">Login</a>
				</div>
			</div>
            {% endif %}

        <div class="middle companyheader">
            <div class="wp">
                <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                <div class="head fl">
                    <h1>
                        Geek Education
                        <img src="{% static 'images/authentication.png' %}"/>
                        <img src="{% static 'images/gold.png' %}"/>
                    </h1>
                    <p class="fl">
                        <span class="fl" style="margin-top:8px;color:#848484;">Hot index: </span>
                        <span class="precision company-credit" data-star-scope="5.0"></span>
                        <span class="key">{{ course_org.fav_nums }}</span>
                    </p>
                </div>
                <div class="btn fr collectionbtn  notlogin
                     "data-favid="22" data-fav-type="1">
                     {% if has_fav %}Added{% else %}Collection{% endif %}
                </div>
            </div>
        </div>
    </div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">Main</a>></li>
			<li><a href="{% url "org:org_list" %}">Organization</a>></li>
			<li>{% block page_title_path %}Organization Details{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">Organization</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">Courses</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">Description</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">Teacher</a></li>
			</ul>
		</div>

{% block right_form %}
{% endblock %}
    </div>
</section>

<!--sidebar end-->
<!--header start-->
{#</div>#}
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url "org:add_fav" %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == 'Please login first!'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path : "{% static 'images' %}",
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['Worst', 'bad', 'Average', 'Good', 'Excellent'],
                    noRatedMsg  : 'No comments yet.',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function() {
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , 'Collection');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>